sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.22.0

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

script:
  - sudo service mysql stop
  - cd docker
  - docker-compose -f docker-compose-e2e.yml up --build
  - pwd
  - cd new
  - ls -la
