version: '3'

services:

  builder-backend:
    container_name: builder-backend
    build:
      context: ../backend-builder
      dockerfile: Dockerfile-E2E
    ports:
      - 8080:8080
    restart: on-failure
    command: bash -c "mvn -f usr/src/spring/pom.xml test package && cd usr/src/spring/target && ls -la"
    volumes:
      - ./new:/usr/src/spring/target
    networks:
      - bldr

networks:
  bldr:
    driver: bridge
